### ISSUE TITLE
I can't set header_cover image from my computer

### ISSUE THREAD

**Issue by afaki077** [gilsondev/pelican-clean-blog#2]
I have png image in this path in my computer ``/home/ali/blog/content/mypic.png``
when i set metadata 
i'm using markdown
```markdown
Header_Cover: /home/ali/blog/content/mypic.png
```

nothing happen but it worked when I tried it from URL in the internet

**Comment by duskox** [comment]
I have tried setting header image as stated, in pelicanconf.py to define:

HEADER_COVER = '/images/header-bg.png'

But the problem is that it only works on Articles and not Pages. Then I tried doing what you did, to set an image for header in Page metadata...then I get it as header background image but I also get it stretched as background image for content and that I do not want.

I am trying to get it working by changing something in base.html and page.html...
